version: "3.8"

services:
  hand-gesture-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hand-gesture-nn-container
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - PYTHONUNBUFFERED=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/app
    devices:
      - "/dev/video0:/dev/video0"
    stdin_open: true
    tty: true
    restart: unless-stopped
