model_path: "models/hand_landmarker.task"
model_gesture: "models/gesture_model.mat"
fps: 30
hand_landmarks_metadata:
  # mcp: stands for `metacarpophalangeal` joint
    # vietnamese: khớp bàn - ngón tay (hay còn gọi là khớp đốt ngón gần gốc nhất, chính là khớp xương "nắm đấm" khi bạn nắm tay lại)
  # pip: stands for `proximal interphalageal` joint
    # vietnamese: khớp liên ngón gần (Khớp đốt ngón tay ở giữa, nằm gần lòng bàn tay hơn so với khớp chót)
  # dip: stands for `distal interphalangeal` joint
    # vietnamese: khớp liên ngon xa (khớp đốt ngón tay nằm gần móng tay/ đầu ngón tay nhất)
  # tip: stands for `finger-tip`
    # vietnamese: đầu ngón tay (điểm mút cùng của ngón tay)
  # cmc: stands for `carpometacarpal` joint 
    # vietnamese: khớp cổ - bàn tay (khớp nối giữa các xương cổ tay và xương bàn tay)
  - 0: wrist
  - 1: thumb_cmc
  - 2: thumb_mcp
  - 3: thumb_ip
  - 4: thumb_tip
  - 5: index_finger_mcp
  - 6: index_finger_pip
  - 7: index_finger_dip
  - 8: index_finger_tip
  - 9: middle_finger_mcp
  - 10: middle_finger_pip
  - 11: middle_finger_dip
  - 12: middle_finger_tip
  - 13: ring_finger_mcp
  - 14: ring_finger_pip
  - 15: ring_finger_dip
  - 16: ring_finger_tip
  - 17: pinky_mcp
  - 18: pinky_pip
  - 19: pinky_dip
  - 20: pinky_tip

connections:
  # Thumb
  - [0, 1]
  - [1, 2]
  - [2, 3]
  - [3, 4]

  # Index
  - [0, 5]
  - [5, 6]
  - [6, 7]
  - [7, 8]

  # Middle
  - [5, 9]
  - [9, 10]
  - [10, 11]
  - [11, 12]

  # Ring
  - [9, 13]
  - [13, 14]
  - [14, 15]
  - [15, 16]

  # Little
  - [13, 17]
  - [17, 18]
  - [18, 19]
  - [19, 20]

  # Palm
  - [0, 17]

sensors:

  # Thumb
  cmc1_f:
    type: flexion
    parent: 0
    joint: 1
    child: 2

  cmc1_a:
    type: abduction
    parent: 0
    joint: 1
    child: 2
    ref_finger: [0,5,6] 

  mcp1:
    type: flexion
    parent: 1
    joint: 2
    child: 3

  ip1:
    type: flexion
    parent: 2
    joint: 3
    child: 4

  # Index
  mcp2_f:
    type: flexion
    parent: 0
    joint: 5
    child: 6

  mcp2_a:
    type: abduction
    parent: 0
    joint: 5
    child: 6
    ref_finger: [0,9,10]
    enabled: false      # Dataset column is NaN

  pip2:
    type: flexion
    parent: 5
    joint: 6
    child: 7

  dip2:
    type: flexion
    parent: 6
    joint: 7
    child: 8

  # Middle
  mcp3_f:
    type: flexion
    parent: 0
    joint: 9
    child: 10

  pip3:
    type: flexion
    parent: 9
    joint: 10
    child: 11

  dip3:
    type: flexion
    parent: 10
    joint: 11
    child: 12

  # Ring
  mcp4_f:
    type: flexion
    parent: 0
    joint: 13
    child: 14

  mcp4_a:
    type: abduction
    parent: 0
    joint: 13
    child: 14
    ref_finger: [0,9,10]

  pip4:
    type: flexion
    parent: 13
    joint: 14
    child: 15

  dip4:
    type: flexion
    parent: 14
    joint: 15
    child: 16

  # Little
  cmc5:
    type: flexion
    parent: 0
    joint: 17
    child: 18

  mcp5_f:
    type: flexion
    parent: 0
    joint: 17
    child: 18

  mcp5_a:
    type: abduction
    parent: 0
    joint: 17
    child: 18
    ref_finger: [0,13,14]

  pip5:
    type: flexion
    parent: 17
    joint: 18
    child: 19

  dip5:
    type: flexion
    parent: 18
    joint: 19
    child: 20

  # Wrist
  # wrist_f:
  #   type: wrist_flexion
  #   parent: null
  #   joint: 0
  #   child: null

  # wrist_a:
  #   type: wrist_abduction
  #   parent: null
  #   joint: 0
  #   child: null  

dimension_activities:
  - classes: 200
    activities: "Unknown"
    
  - classes: 201
    activities: "Thumb up"

  - classes: 202
    activities: "Extension of index and middle, flexion of the others"

  - classes: 203
    activities: "Flexion of ring and little finger, extension of the others"

  - classes: 204
    activities: "Thumb opposing base of little finger"

  - classes: 205
    activities: "Abduction of all fingers"

  - classes: 206
    activities: "Fingers flexed together in fist"

  - classes: 207
    activities: "Pointing index"

  - classes: 208
    activities: "Adduction of extended fingers"

  - classes: 209
    activities: "Wrist supination (axis: middle finger)"

  - classes: 210
    activities: "Wrist pronation (axis: middle finger)"

  - classes: 211
    activities: "Wrist supination (axis: little finger)"

  - classes: 212
    activities: "Wrist pronation (axis: little finger)"

  - classes: 213
    activities: "Wrist flexion"

  - classes: 214
    activities: "Wrist extension"

  - classes: 215
    activities: "Wrist extension with closed hand"

  - classes: 216
    activities: "Wrist ulnar deviation"

  - classes: 217
    activities: "Wrist radial deviation"
  
  - classes: 301
    activities: "Large diameter grasp"

  - classes: 302
    activities: "Small diameter grasp (power grip)"

  - classes: 303
    activities: "Fixed hook grasp"

  - classes: 304
    activities: "Index finger extension grasp"

  - classes: 305
    activities: "Medium wrap"

  - classes: 306
    activities: "Ring grasp"

  - classes: 307
    activities: "Prismatic four fingers grasp"

  - classes: 308
    activities: "Stick grasp"

  - classes: 309
    activities: "Writing tripod grasp"

  - classes: 310
    activities: "Power sphere grasp"

  - classes: 311
    activities: "Three finger sphere grasp"

  - classes: 312
    activities: "Precision sphere grasp"

  - classes: 313
    activities: "Tripod grasp"

  - classes: 314
    activities: "Prismatic pinch grasp"

  - classes: 315
    activities: "Tip pinch grasp"

  - classes: 316
    activities: "Quadpod grasp"

  - classes: 317
    activities: "Lateral grasp"

  - classes: 318
    activities: "Parallel extension grasp"

  - classes: 319
    activities: "Extension type grasp"

  - classes: 320
    activities: "Power disk grasp"

  - classes: 321
    activities: "Open a bottle with a tripod grasp"

  - classes: 322
    activities: "Turn a screw (grasp the screwdriver with a stick grasp)"

  - classes: 323
    activities: "Cut something (grasp the knife with an index finger extension grasp)"